name: MERN Project CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update instance packages
        run: sudo apt update && sudo apt upgrade -y

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build

      - name: Install Apache2 server
        run: sudo apt install -y apache2

      - name: Set correct permissions for Apache2
        run: sudo chown ubuntu:ubuntu /var/www/html/

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Copy build folder to Apache2 server
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build/*
          host: ${{ secrets.HOST }}
          remote: /var/www/html/
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}

      - name: Start Backend with PM2
        run: pm2 start backend/index.js --name "mern-app"

      - name: Save PM2 process list
        run: pm2 save

      - name: Ensure PM2 starts on reboot
        run: pm2 startup systemd

      - name: Restart Apache2 server
        run: sudo systemctl restart apache2
