name: MERN PROJECT DEPLOY
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: chekcout repository
        uses: actions/checkout@v3

      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Npm
        run: npm install

      - name: build the project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps: 
      
      - name: Install apache2 server
        run: sudo apt install apache2 -y

      - name: Set correct permissions for Apache2
        run: sudo chown ubuntu:ubuntu /var/www/html/

      - name: Install pm2
        run: npm install -g pm2

      - name: copy the build folder in apache2 server
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build/*
          host: ${{ secrets.HOST }}
          remote: /var/www/html/
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}

      - name: Start Applicationwith pm2
        run: pm2 start backend/index.js --name "mern-app"

      - name: save PM2 process list
        run: pm2 save

      - name: Restart PM2 on reboot
        run: pm2 startup systemd

      - name: restart apache2 server
        run: sudo systemctl restart apache2

    
      
    
